In [1]:
# Assignment 3 Task - 1 Question - 1
a = 5
b = 0
try:
    print(a/b)
except Exception as e:
    print(e)

division by zero


In [12]:
# Assignment 3 Task - 1 Question - 2 

subjects = ["Americans ","Indians "]
verbs = ["play ","watch "]
objects = ["Baseball ","Cricket "]

a = sorted(subjects*4)
b = sorted(verbs*2)
c = objects*2
d = list(filter(lambda x: x == 'Americans ',a))
e = list(filter(lambda x: x != 'Americans ',a))
f = list(zip(d,b,c))
g = list(zip(e,b,c))
h, i, j, k = f[0], f[1], f[2], f[3]
l, m, n, o = g[0], g[1], g[2], g[3]
p, q, r, s = ''.join(h), ''.join(i), ''.join(j), ''.join(k)
t, u, v, w = ''.join(l), ''.join(m), ''.join(m), ''.join(o)
print(p, q, r, s, sep = '\n')
print(t, u, v, w, sep = '\n')

Americans play Baseball 
Americans play Cricket 
Americans watch Baseball 
Americans watch Cricket 
Indians play Baseball 
Indians play Cricket 
Indians play Cricket 
Indians watch Cricket 


In [44]:
# Assignment 3 Task - 1 Question - 3

import numpy as np
def atv_mat(inp_vec, n, incre = False):

    if incre == False:
        out_mat = np.array([x**(n-1-i) for x in inp_vec for i in range(n)]).reshape(inp_vec.size,n)
    elif incre == True:
        out_mat = np.array([x**i for x in inp_vec for i in range(n)]).reshape(inp_vec.size,n)
    return out_mat

inp_vec = np.array([1,2,3,4,5])
n = 5
out_mat_dec = atv_mat(inp_vec,n,False)
out_mat_inc = atv_mat(inp_vec,n,True)
print('Output matrix in decreasing order: ',out_mat_dec, sep='\n')
print('Output matrix in increasing order: ',out_mat_inc, sep='\n')

Output matrix in decreasing order: 
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
Output matrix in increasing order: 
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
